import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JS TEAM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Nuestro Equipo
        </h2>

        <p className={styles.description}>
         somos un grupo de apasionados que se divierten construyendo tus sueños 
        </p>

        <div>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Nicolas</h2>
            <Image src="/profile.jpeg" alt="nicolas Profile" className={styles.profile} width={150} height={150} />
            <p>Frontend <br></br> Developer</p>
            <hr></hr>
          </a>

          <a href="https://github.com/gabrielcontrerasv" className={styles.card}>
            <h2>Gabriel</h2>
            <Image src="/gabriel.jpg" alt="gabriel profiel" className={styles.profile} width={150} height={150} />
            <p>Backend <br></br> Developer</p>
            <hr></hr>
          </a>

          <a
            href="https://github.com/TiagoBG"
            className={styles.card}
          >
            <h2>Santiago</h2>
            <Image src="/tiago.jpg" alt="santiago profile" className={styles.profile}  width={150} height={150} />
            <p>Web <br></br>Developer</p>
            <hr></hr>
          </a>

          <a
            href="https://github.com/marcosihe"
            className={styles.card}
          >
            <h2>Marco </h2>
            <Image src="/marcos.png" alt="marco profile" className={styles.profile}  width={150} height={150} />
            <p>Web <br></br>Developer</p>
            <hr></hr>
          </a>
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.teaminternational.com/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by 
            <Image src="/team.png" alt="Team Logo" width={72} height={60} />
        </a>
      </footer>
    </div>
  )
}
